# Generated by Django 4.2.7 on 2023-11-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="photo",
            field=models.ImageField(upload_to="static/pet_photos/"),
        ),
    ]
