# Generated by Django 4.2.7 on 2023-11-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0002_alter_pet_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[("small", "Small"), ("medium", "Medium"), ("large", "Large")],
                max_length=10,
                null=True,
            ),
        ),
    ]
