# Generated by Django 4.2.7 on 2023-11-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0004_remove_pet_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[("small", "Small"), ("medium", "Medium"), ("large", "Large")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="species",
            field=models.CharField(
                choices=[("dog", "Dog"), ("cat", "Cat")], max_length=50, null=True
            ),
        ),
    ]
