# Generated by Django 4.2.7 on 2023-11-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0005_pet_size_pet_species"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="temperament",
            field=models.CharField(
                choices=[
                    ("friendly", "Friendly"),
                    ("calm", "Calm"),
                    ("playful", "Playful"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
