# Generated by Django 4.2.7 on 2023-11-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0006_pet_temperament"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("specialization", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("phone_number", models.CharField(max_length=15)),
                (
                    "profile_photo",
                    models.ImageField(blank=True, null=True, upload_to="vet_photos"),
                ),
                ("education_history", models.TextField(blank=True)),
                ("review", models.TextField(blank=True)),
            ],
        ),
    ]
