# Generated by Django 4.2.7 on 2023-11-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0007_vet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vet",
            name="profile_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/vet_photos/"
            ),
        ),
    ]
